FoodApp2/Models/DB_Entities.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;
namespace FoodApp2.Models
{
    public class DB_Entities : DbContext
    {
        public DB_Entities() : base("FoodDB") { }
        public DbSet<User> Users { get; set; }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //Database.SetInitializer<demoEntities>(null);
            modelBuilder.Entity<User>().ToTable("Users");
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();

            base.OnModelCreating(modelBuilder);


        }
    }
}

FoodApp2/Models/ErrorViewModel.cs
using System;

namespace FoodApp2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FoodApp2/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace FoodApp2.Models
{
    public class User
    {
        [Key, Column(Order = 1)]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int idUser { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 3)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 3)]
        public string LastName { get; set; }
        [Required]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}")]
        public string Email { get; set; }

        [Required]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,15}$")]

        public string Password { get; set; }

        [NotMapped]
        [Required]
        [System.ComponentModel.DataAnnotations.Compare("Password")]
        public string ConfirmPassword { get; set; }
        public string FullName()
        {
            return this.FirstName + " " + this.LastName;
        }
    }
}

FoodApp2/Controllers/Api/FoodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using FoodApp2.Service.Foods;
using Microsoft.AspNetCore.Mvc;

namespace FoodApp2.Controllers.Api
{
    [Route("api/[controller]/[action]")]
    public class FoodsController : Controller
    {
        private readonly IFoodService _foodService;
        private readonly IFoodTypeService _foodTypeService;

        public FoodsController(
            IFoodService foodService,
            IFoodTypeService foodTypeService
        )
        {
            _foodService = foodService;
            _foodTypeService = foodTypeService;
        }

        public async Task<IActionResult> AllFoods()
        {
            var foods = await _foodService.GetAllFoodsAsync();

            return Json(new { isSuccess = true, data = foods });
        }

        public async Task<IActionResult> FoodsByType(long id)
        {
            var foods = await _foodService.GetAllFoodsByFoodTypeIdAsync(id);

            return Json(new { isSuccess = true, data = foods });
        }
    }
}

FoodApp2/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace FoodApp2.Controllers
{
    public abstract class BaseController 
    {
        public BaseController()
        {

        }
    }
}

FoodApp2/Controllers/FoodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FoodApp2.Service.Foods;
using Microsoft.AspNetCore.Mvc;

namespace FoodApp2.Controllers
{
    public class FoodsController : BaseController
    {
        private readonly IFoodService _foodService;
        private readonly IFoodTypeService _foodTypeService;

        public FoodsController(
            IFoodService foodService,
            IFoodTypeService foodTypeService
        )
        {
            _foodService = foodService;
            _foodTypeService = foodTypeService;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        [Route("foods/details/{id}/{name}")]
        public async Task<IActionResult> Details(long id)
        {
            var food = await _foodService.GetFoodByIdAsync(id);

            return View(food);
        }

        [Route("foods/type/{id}/{name}")]
        public async Task<IActionResult> FoodsByType(long id, string name)
        {
            var foods = await _foodService.GetAllFoodsByFoodTypeIdAsync(id);

            var foodType = await _foodTypeService.GetFoodTypeByIdAsync(id);
            ViewBag.FoodType = foodType?.Name ?? name;
              ViewBag.FoodTypeId = foodType.Id;

            return View(foods);
        }
    }
}

FoodApp2/Controllers/HomeController.cs
using System;
using System.Text;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FoodApp2.Models;
using System.Security.Cryptography;
namespace FoodApp2.Controllers
{
    public class HomeController : Controller
    {
        private DB_Entities _db = new DB_Entities();
        // GET: Home
        public ActionResult Index()
        {
            if (Session["idUser"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
        }

        //GET: Register

        public ActionResult Register()
        {
            return View();
        }

        //POST: Register
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(User _user)
        {
            if (ModelState.IsValid)
            {
                var check = _db.Users.FirstOrDefault(s => s.Email == _user.Email);
                if (check == null)
                {
                    _user.Password = GetMD5(_user.Password);
                    _db.Configuration.ValidateOnSaveEnabled = false;
                    _db.Users.Add(_user);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.error = "Email already exists";
                    return View();
                }


            }
            return View();


        }

        public ActionResult Login()
        {
            return View();
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string email, string password)
        {
            if (ModelState.IsValid)
            {


                var f_password = GetMD5(password);
                var data = _db.Users.Where(s => s.Email.Equals(email) && s.Password.Equals(f_password)).ToList();
                if (data.Count() > 0)
                {
                    //add session
                    Session["FullName"] = data.FirstOrDefault().FirstName + " " + data.FirstOrDefault().LastName;
                    Session["Email"] = data.FirstOrDefault().Email;
                    Session["idUser"] = data.FirstOrDefault().idUser;
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.error = "Login failed";
                    return RedirectToAction("Login");
                }
            }
            return View();
        }


        //Logout
        public ActionResult Logout()
        {
            Session.Clear();//remove session
            return RedirectToAction("Login");
        }



        //create a string MD5
        public static string GetMD5(string str)
        {
            MD5 md5 = new MD5CryptoServiceProvider();
            byte[] fromData = Encoding.UTF8.GetBytes(str);
            byte[] targetData = md5.ComputeHash(fromData);
            string byte2String = null;

            for (int i = 0; i < targetData.Length; i++)
            {
                byte2String += targetData[i].ToString("x2");

            }
            return byte2String;
        }

    }
}

FoodApp2/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace FoodApp2.Controllers
{
    public class ShoppingCartController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

FoodApp2/Views/Foods/Details.cshtml
 @using FoodApp2.Data.Entities.Foods
@using FoodApp2.Core.Extensions

@model Food
@{
    ViewData["Title"] = "Foods - " + Model.Name;
}


<div class="row">
    <div class="col-md-3">
        <div class="panel panel-primary sidebar">
            <div class="panel-heading">
                <h3 class="panel-title">Categories</h3>
            </div>

            <foodtypesidebar></foodtypesidebar>
        </div>
    </div>
    <div class="col-md-9">
        <h1>@Model.Name</h1>

        <div class="row">
            <div class="col-md-7">
                <img src="/images/@Model.ImageUrl" class="img-responsive" />

            </div>

            <div class="col-md-5">
                <div class="panel panel-default">
                    <div id="cartApp" class="panel-body">
                        <p>
                            @Model.ShortDescription
                        </p>
                        <div class="spacing"></div>
                        <div class="detail-pricing">
                            <span>$</span><span>@Model.Price</span>
                        </div>
                        <div class="spacing"></div>
                        <div>
                            <strong>Quantity</strong> <input v-model="item.quantity" type="number" min="1" class="form-control" value="1" style="width: 100px;" />
                        </div>
                        <div class="spacing"></div>
                        <div>
                            <button v-bind:data-id="@Model.Id" class="btn btn-success btn-lg btn-block" @@click="addToCart(item)">Add to Cart</button>
                        </div>
                    </div>
                </div>

            </div>

            <div class="col-md-12">
                <div class="spacing"></div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>Description</h4>
                    </div>
                    <div class="panel-body">
                        <p>@(string.IsNullOrWhiteSpace(Model.LongDescription) ? Model.ShortDescription : Model.LongDescription)</p>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        $(function () {


            var cartApp = new Vue({
                el: "#cartApp",
                shoppingCartStore,
                data: {
                    cart: [],
                    item: { id: @Model.Id, name: '@Model.Name', price: @Model.Price, quantity: 1 },
                },
                methods: {
                    addToCart(item) {
                        shoppingCartStore.commit('addToCart', item);
                        shoppingCartStore.commit('saveCart');
                    }
                }
            });
        });
    </script>
}

FoodApp2/Views/Foods/FoodsByType.cshtml
@using FoodApp2.Data.Entities.Foods
@using FoodApp2.Core.Extensions
@model IList<Food>
@{
    ViewData["Title"] = "Foods - " + ViewBag.FoodType;
}



<div class="row">
    <div class="col-md-3">
        <div class="panel panel-primary sidebar">
            <div class="panel-heading">
                <h3 class="panel-title">Categories</h3>
            </div>

            <foodtypesidebar></foodtypesidebar>
        </div>
    </div>
    <div class="col-md-9">
        <h2>@ViewBag.FoodType</h2>

        <div id="foodListingApp" class="row">
            <div class="col-md-4" v-for="food in foodData">
                <div class="card" v-on:click="productClicked('/foods/details/' + food.id + '/' + food.seoFriendlyUrl)">
                    <img class="card-img img-responsive" v-bind:src="'/images/' + food.imageUrl">
                    <div class="card-body">
                        <div class="card-title">{{ food.name }}</div>
                        <div class="card-pricing">
                            <span>$</span><span>{{ food.price }}</span>
                        </div>
                    </div>
                </div>
                <button v-bind:data-id="food.id" class="btn btn-success btn-sm btn-block" @@click="addToCart(food)">Add to Cart</button>
            </div>
        </div>
    </div>
</div>

@section Scripts
    {
    <script type="text/javascript">
        $(function () {
            var foodListingApp = new Vue({
                el: "#foodListingApp",
                data: {
                    foodData: {},
                },
                computed: {
                    btnSize: function() {
                        return "btn-sm";
                    }
                },
                methods: {
                    productClicked: function (url) {
                        window.location.href = url;
                    },
                    addToCart(food) {
                        shoppingCartStore.commit('addToCart', food);
                        shoppingCartStore.commit('saveCart');
                    }
                }
            });

            $.ajax({
                url: "/api/Foods/FoodsByType/",
                data: {
                    id: "@ViewBag.FoodTypeId"
                },
                success: function (result) {
                    if (result.isSuccess) {
                        foodListingApp.foodData = result.data;
                    }
                }
            });
        });
    </script>
}

FoodApp2/Views/Foods/Index.cshtml
@{
    ViewData["Title"] = "Foods";
}



<div class="row">
    <div class="col-md-3">
        <div class="panel panel-primary sidebar">
            <div class="panel-heading">
                <h3 class="panel-title">Categories</h3>
            </div>

            <foodtypesidebar></foodtypesidebar>
        </div>
    </div>
    <div class="col-md-9">
        <h2>Foods</h2>

        <div id="foodListingApp" class="row">
            <div class="col-md-4" v-for="food in foodData">
                <div class="card" v-on:click="productClicked('/foods/details/' + food.id + '/' + food.seoFriendlyUrl)">
                    <img class="card-img img-responsive" v-bind:src="'/images/' + food.imageUrl">
                    <div class="card-body">
                        <div class="card-title">{{ food.name }}</div>
                        <div class="card-pricing">
                            <span>$</span><span>{{ food.price }}</span>
                        </div>
                    </div>
                </div>
                <button v-bind:data-id="food.id" class="btn btn-success btn-sm btn-block" @@click="addToCart(food)">Add to Cart</button>
            </div>
        </div>
    </div>
</div>

@section Scripts
    {
    <script type="text/javascript">
        $(function () {
            var foodListingApp = new Vue({
                el: "#foodListingApp",
                data: {
                    foodData: {},
                },
                computed: {
                    btnSize: function () {
                        return "btn-sm";
                    }
                },
                methods: {
                    productClicked: function (url) {
                        window.location.href = url;
                    },
                    addToCart(food) {
                        food.quantity = 1;
                        shoppingCartStore.commit('addToCart', food);
                        shoppingCartStore.commit('saveCart');
                    }
                }
            });

            $.ajax({
                url: "/api/Foods/AllFoods",
                success: function (result) {
                    if (result.isSuccess) {
                        foodListingApp.foodData = result.data;
                    }
                }
            });
        });
    </script>
}

FoodApp2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Foods";
}

<div class="card-body">
    @if (Session["FullName"] != null)
    {
        <p>Name: @Session["FullName"].ToString()</p>
        <p>Email: @Session["Email"].ToString()</p>
        <a href="@Url.Action("Logout","Home")" class="btn btn-warning">Logout</a>
    }
</div>

<div class="row">
    <div class="col-md-3">
        <div class="panel panel-primary sidebar">
            <div class="panel-heading">
                <h3 class="panel-title">Categories</h3>
            </div>

            <foodtypesidebar></foodtypesidebar>
        </div>
    </div>
    <div class="col-md-9">
        <h2>Foods</h2>

        <div id="foodListingApp" class="row">
            <div class="col-md-4" v-for="food in foodData">

                <div class="card" v-on:click="productClicked('/foods/details/' + food.id + '/' + food.seoFriendlyUrl)">
                    <img class="card-img img-responsive" v-bind:src="'/images/' + food.imageUrl">
                    <div class="card-body">
                        <div class="card-title">{{ food.name }}</div>
                        <div class="card-pricing">
                            <span>$</span><span>{{ food.price }}</span>
                        </div>
                    </div>
                </div>
                <button v-bind:data-id="food.id" class="btn btn-success btn-sm btn-block" @@click="addToCart(food)">Add to Cart</button>
            </div>
        </div>
    </div>
</div>
@section Scripts
    {
    <script type="text/javascript">
        $(function () {
            var foodListingApp = new Vue({
                el: "#foodListingApp",
                data: {
                    foodData: {},
                },
                computed: {
                    btnSize: function () {
                        return "btn-sm";
                    }
                },
                methods: {
                    productClicked: function (url) {
                        window.location.href = url;
                    },
                    addToCart(food) {
                        food.quantity = 1;
                        shoppingCartStore.commit('addToCart', food);
                        shoppingCartStore.commit('saveCart');
                    }
                }
            });

            $.ajax({
                url: "/api/Foods/AllFoods",
                success: function (result) {
                    if (result.isSuccess) {
                        foodListingApp.foodData = result.data;
                    }
                }
            });
        });
    </script>
}

FoodApp2/Views/Home/Login.cshtml
@model FoodApp2.Models.User
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row justify-content-md-center">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                Login
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Login", "Home", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        @Html.LabelFor(m => m.Email)
                        @Html.TextBoxFor(m => m.Email, "", new { @class = "form-control", @placeholder = "Email" })

                    </div>

                    <div class="form-group">
                        @Html.LabelFor(m => m.Password)
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Password" })
                    </div>
                    <div class="form-group">
                        <input type="submit" name="submit" class="btn btn-primary" value="Login" />
                    </div>
                    <div class="form-group">
                        <input type="submit" name="submit" class="btn btn-primary" value="Register" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>

FoodApp2/Views/Home/Register.cshtml
@model FoodApp2.Models.User

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row justify-content-md-center">
    <div class="col-md-5">
        @using (Html.BeginForm("Register", "Home", FormMethod.Post))
        {
            //@Html.ValidationSummary()
            @Html.AntiForgeryToken()

            <div class="card">
                <div class="card-header">
                    <div class="card-title">Register</div>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        @Html.LabelFor(m => m.FirstName)
                        @Html.TextBoxFor(m => m.FirstName, "", new { @class = "form-control", @placeholder = "First Name" })
                        @Html.ValidationMessageFor(m => m.FirstName, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.LastName)
                        @Html.TextBoxFor(m => m.LastName, "", new { @class = "form-control", @placeholder = "Last Name" })
                        @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "badge badge-danger" })

                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Email)
                        @Html.TextBoxFor(m => m.Email, "", new { @class = "form-control", @placeholder = "Email" })
                        @Html.ValidationMessageFor(m => m.Email, "", new { @class = "badge badge-danger" })
                        @if (ViewBag.error != null)
                        {
                            <span class="badge badge-danger">@ViewBag.error</span>
                        }
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Password)
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Password" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "badge badge-danger" })
                    </div>
               
                   <div class="form-group">
                       @Html.LabelFor(m => m.ConfirmPassword)
                        @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control", @placeholder = "Confirm Password" })
                        @Html.ValidationMessageFor(m => m.ConfirmPassword, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        <input type="submit" name="submit" class="btn btn-danger" value="Register" />
                    </div>
                </div>
            </div>

        }
    </div>
</div>

FoodApp2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FoodDelivery</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">FoodDelivery</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a id="shoppingCartBadge" asp-controller="ShoppingCart" asp-action="Index"><i class="fa fa-shopping-cart fa-5" aria-hidden="true"></i> <span class="badge badge-red">{{quantity}}</span></a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - FoodDelivery</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/vue@2.5.21/dist/vue.js"></script>
        <script src="https://unpkg.com/vuex@3.1.0/dist/vuex.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="https://cdn.jsdelivr.net/npm/vue@2.5.21/dist/vue.min.js"></script>
        <script src="https://unpkg.com/vuex@3.1.0/dist/vuex.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    <script src="~/js/bootstrap-notify.min.js" asp-append-version="true"></script>

    <script>
        var shoppingCartBadgeApp = new Vue({
            el: "#shoppingCartBadge",
            data: {
                quantity: 0
            }
        });

        shoppingCartBadgeApp.quantity = shoppingCartStore.getters.getCart.length;
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>

FoodApp2/Views/ShoppingCart/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Shopping Cart</h2>
<p>&nbsp;</p>
<table id="shoppingCartApp" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th width="10%">Quantity</th>
            <th>Price ($)</th>
            <th>Total Price ($)</th>
        </tr>
    </thead>
    <tbody>
        <tr v-for="item in cart">
            <td>
                {{ item.name }}
            </td>
            <td>
                <input type="number" v-model="item.quantity" class="form-control" />
            </td>
            <td>
                {{ item.price }}
            </td>
            <td>
                {{ item.quantity * item.price }}
            </td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">
                <strong>Total</strong>
            </td>
            <td>
                <span class="shopping-cart-total-amount"><strong>{{ totalPrice() }}</strong></span>
            </td>
        </tr>
    </tfoot>
</table>

@section Scripts
    {
    <script type="text/javascript">
        $(function () {
            var cart = shoppingCartStore.getters.getCart;

            var shoppingCartApp = new Vue({
                el: "#shoppingCartApp",
                data: {
                    cart: cart,
                },
                methods: {
                    totalPrice: function () {
                        var totalPrice = 0;
                        for (var index = 0; index < cart.length; index++) {
                            totalPrice += cart[index].price * cart[index].quantity;
                        }

                        return totalPrice;
                    }
                }
            });



            shoppingCartApp.totalPrice = totalPrice;
        });
    </script>
}